const mongoose = require("mongoose");
const db = require("../models");

mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost/myDatabase");

// const UserSeed = [
//   {
//     email: "hkiddell0@sphinn.com",
//     password: "FzHkL2dlwr",
//     category: "Player",
//     name: "Herc Kiddell",
//     link: "http://dummyimage.com/113x119.bmp/ff4444/ffffff",
//     teamID: "5eab235fd0d01c678e74e9f8",
//   },
//   {
//     email: "manstiss1@angelfire.com",
//     password: "mqv6DF9RwM2",
//     category: "Player",
//     name: "Melesa Anstiss",
//     link: "http://dummyimage.com/189x130.png/cc0000/ffffff",
//     teamID: "5eab235fd0d01c678e74e9f8",
//   },
//   {
//     email: "amctrustie2@skyrock.com",
//     password: "MYRpgP5YNnkO",
//     category: "Player",
//     name: "Adan McTrustie",
//     link: "http://dummyimage.com/132x149.png/dddddd/000000",
//   },
//   {
//     email: "ple3@arizona.edu",
//     password: "1qMaLZjXfbHE",
//     category: "Player",
//     name: "Phillip Le Grove",
//     link: "http://dummyimage.com/213x145.png/dddddd/000000",
//   },
//   {
//     email: "dsizey4@engadget.com",
//     password: "kuTmRR",
//     category: "Player",
//     name: "Dido Sizey",
//     link: "http://dummyimage.com/196x185.jpg/ff4444/ffffff",
//   },
//   {
//     email: "jgatheral5@hc360.com",
//     password: "yTRGpoSB",
//     category: "Player",
//     name: "Jeff Gatheral",
//     link: "http://dummyimage.com/206x224.jpg/dddddd/000000",
//   },
//   {
//     email: "jhallad6@themeforest.net",
//     password: "kSs90VOqD",
//     category: "Player",
//     name: "Julita Hallad",
//     link: "http://dummyimage.com/107x210.jpg/5fa2dd/ffffff",
//   },
//   {
//     email: "ikunert7@booking.com",
//     password: "wa1771u7Jc",
//     category: "Player",
//     name: "Isidor Kunert",
//     link: "http://dummyimage.com/199x142.jpg/cc0000/ffffff",
//   },
//   {
//     email: "slumby8@ftc.gov",
//     password: "976KLeC19k",
//     category: "Player",
//     name: "Simeon Lumby",
//     link: "http://dummyimage.com/151x201.jpg/ff4444/ffffff",
//   },
//   {
//     email: "npacher9@jugem.jp",
//     password: "pAgs4MsYXzH",
//     category: "Player",
//     name: "Noah Pacher",
//     link: "http://dummyimage.com/215x240.jpg/5fa2dd/ffffff",
//   },
//   {
//     email: "aabletta@vinaora.com",
//     password: "em89p1Agm",
//     category: "Player",
//     name: "Amalie Ablett",
//     link: "http://dummyimage.com/155x143.png/5fa2dd/ffffff",
//   },
//   {
//     email: "iplewmanb@163.com",
//     password: "zk2CII3nLo",
//     category: "Player",
//     name: "Isadora Plewman",
//     link: "http://dummyimage.com/111x221.jpg/5fa2dd/ffffff",
//   },
//   {
//     email: "jeaklyc@archive.org",
//     password: "MxA5ugpo51wt",
//     category: "Player",
//     name: "Jermayne Eakly",
//     link: "http://dummyimage.com/182x147.bmp/5fa2dd/ffffff",
//   },
//   {
//     email: "dpringled@bravesites.com",
//     password: "8CHXWoCMm",
//     category: "Player",
//     name: "Doti Pringle",
//     link: "http://dummyimage.com/129x146.bmp/5fa2dd/ffffff",
//   },
//   {
//     email: "gfendleye@utexas.edu",
//     password: "Kzr5Nlg",
//     category: "Player",
//     name: "Gerardo Fendley",
//     link: "http://dummyimage.com/113x163.png/ff4444/ffffff",
//   },
//   {
//     email: "eespf@seesaa.net",
//     password: "oxWdEZx",
//     category: "Player",
//     name: "Ethan Esp",
//     link: "http://dummyimage.com/148x147.bmp/dddddd/000000",
//   },
//   {
//     email: "fbarnsdaleg@microsoft.com",
//     password: "I7XuBqYlmAE",
//     category: "Player",
//     name: "Fawne Barnsdale",
//     link: "http://dummyimage.com/152x217.jpg/cc0000/ffffff",
//   },
//   {
//     email: "mossennah@booking.com",
//     password: "qS4QZZjad",
//     category: "Player",
//     name: "Minette Ossenna",
//     link: "http://dummyimage.com/103x131.bmp/ff4444/ffffff",
//   },
//   {
//     email: "mslayi@sohu.com",
//     password: "mT3PsBD6sd",
//     category: "Player",
//     name: "Miguela Slay",
//     link: "http://dummyimage.com/159x187.jpg/cc0000/ffffff",
//   },
//   {
//     email: "mskokoej@state.gov",
//     password: "nMDstfU",
//     category: "Player",
//     name: "Melodie Skokoe",
//     link: "http://dummyimage.com/134x249.bmp/ff4444/ffffff",
//   },
//   {
//     email: "tlindhek@archive.org",
//     password: "0Q8P5Gl",
//     category: "Player",
//     name: "Trevar Lindhe",
//     link: "http://dummyimage.com/217x142.png/dddddd/000000",
//   },
//   {
//     email: "edrinkhilll@sphinn.com",
//     password: "zsOg6BYU",
//     category: "Player",
//     name: "Erma Drinkhill",
//     link: "http://dummyimage.com/218x155.bmp/ff4444/ffffff",
//   },
//   {
//     email: "walbinm@cnbc.com",
//     password: "w56PYIcHGal",
//     category: "Player",
//     name: "Weider Albin",
//     link: "http://dummyimage.com/146x169.bmp/5fa2dd/ffffff",
//   },
//   {
//     email: "lhubatschn@about.com",
//     password: "QGr0lBRo",
//     category: "Player",
//     name: "Liane Hubatsch",
//     link: "http://dummyimage.com/146x238.png/5fa2dd/ffffff",
//   },
//   {
//     email: "mbazyletso@wix.com",
//     password: "BIoE0gno",
//     category: "Player",
//     name: "Mattie Bazylets",
//     link: "http://dummyimage.com/218x136.jpg/cc0000/ffffff",
//   },
//   {
//     email: "aanderssonp@sun.com",
//     password: "e6zsuG1r",
//     category: "Player",
//     name: "Arlette Andersson",
//     link: "http://dummyimage.com/140x104.jpg/cc0000/ffffff",
//   },
//   {
//     email: "rsladq@wufoo.com",
//     password: "Qo2qq6dhfZBf",
//     category: "Player",
//     name: "Raimondo Slad",
//     link: "http://dummyimage.com/103x237.jpg/cc0000/ffffff",
//   },
//   {
//     email: "ohuntr@google.it",
//     password: "VLrxc0zEbA7",
//     category: "Player",
//     name: "Onida Hunt",
//     link: "http://dummyimage.com/139x172.png/dddddd/000000",
//   },
//   {
//     email: "hgogertys@google.com.hk",
//     password: "wl1BBoz",
//     category: "Player",
//     name: "Hans Gogerty",
//     link: "http://dummyimage.com/201x151.jpg/cc0000/ffffff",
//   },
//   {
//     email: "klet@google.es",
//     password: "Trt9Eh7InxE",
//     category: "Player",
//     name: "Kahlil Le Estut",
//     link: "http://dummyimage.com/168x155.png/cc0000/ffffff",
//   },
//   {
//     email: "bmacronaldu@springer.com",
//     password: "RaLo1fLpo2Wf",
//     category: "Player",
//     name: "Bevan MacRonald",
//     link: "http://dummyimage.com/135x161.jpg/cc0000/ffffff",
//   },
//   {
//     email: "esarjentv@blogspot.com",
//     password: "jKjgYw",
//     category: "Player",
//     name: "Even Sarjent",
//     link: "http://dummyimage.com/187x205.bmp/cc0000/ffffff",
//   },
//   {
//     email: "cclementetw@tumblr.com",
//     password: "MFSb98",
//     category: "Player",
//     name: "Chen Clementet",
//     link: "http://dummyimage.com/206x190.bmp/ff4444/ffffff",
//   },
//   {
//     email: "etunbridgex@nba.com",
//     password: "ikgYqMLzy",
//     category: "Player",
//     name: "Ermin Tunbridge",
//     link: "http://dummyimage.com/118x195.png/cc0000/ffffff",
//   },
//   {
//     email: "lclewesy@hubpages.com",
//     password: "lGRW4eL",
//     category: "Player",
//     name: "Lisa Clewes",
//     link: "http://dummyimage.com/165x157.jpg/ff4444/ffffff",
//   },
//   {
//     email: "mmenaultz@bbc.co.uk",
//     password: "9wrHSCTM",
//     category: "Player",
//     name: "Myrna Menault",
//     link: "http://dummyimage.com/103x210.png/ff4444/ffffff",
//     teamID: "5eab235fd0d01c678e74e9f8",
//   },
//   {
//     email: "lbaum10@sitemeter.com",
//     password: "ZiALwgmPJ",
//     category: "Player",
//     name: "Lin Baum",
//     link: "http://dummyimage.com/116x225.jpg/5fa2dd/ffffff",
//     teamID: "5eab235fd0d01c678e74e9f8",
//   },
//   {
//     email: "mcastro11@vkontakte.ru",
//     password: "wdkQY0cmA",
//     category: "Player",
//     name: "Molli Castro",
//     link: "http://dummyimage.com/124x234.bmp/5fa2dd/ffffff",
//     teamID: "5eab235fd0d01c678e74e9f8",
//   },
//   {
//     email: "psainte12@infoseek.co.jp",
//     password: "4YVeVTN8d",
//     category: "Player",
//     name: "Portie Sainte Paul",
//     link: "http://dummyimage.com/123x163.png/dddddd/000000",
//     teamID: "5eab235fd0d01c678e74e9f8",
//   },
//   {
//     email: "pbodega13@blog.com",
//     password: "wMfjP8",
//     category: "Player",
//     name: "Portia Bodega",
//     link: "http://dummyimage.com/231x230.png/ff4444/ffffff",
//     teamID: "5eab235fd0d01c678e74e9f8",
//   },
//   {
//     email: "mrottcher14@census.gov",
//     password: "Vc6bPZi",
//     category: "Player",
//     name: "Michael Rottcher",
//     link: "http://dummyimage.com/146x115.jpg/cc0000/ffffff",
//     teamID: "5eab235fd0d01c678e74e9f8",
//   },
//   {
//     email: "jmonteith15@google.com",
//     password: "w8KIoPGr3g",
//     category: "Player",
//     name: "Joli Monteith",
//     link: "http://dummyimage.com/120x160.bmp/5fa2dd/ffffff",
//     teamID: "5eab235fd0d01c678e74e9f8",
//   },
//   {
//     email: "xstoakley16@state.gov",
//     password: "UMkjoYnyoN9Q",
//     category: "Player",
//     name: "Ximenes Stoakley",
//     link: "http://dummyimage.com/177x188.bmp/5fa2dd/ffffff",
//     teamID: "5eab235fd0d01c678e74e9f8",
//   },
//   {
//     email: "nredmore17@unicef.org",
//     password: "wAMjZgHHRJ",
//     category: "Player",
//     name: "Nanci Redmore",
//     link: "http://dummyimage.com/110x178.png/5fa2dd/ffffff",
//     teamID: "5eab235fd0d01c678e74e9f8",
//   },
// ];

// db.User;
// db.User.collection
//   .insertMany(UserSeed)
//   .then((data) => {
//     console.log(data.result.n + " records inserted!");
//     process.exit(0);
//   })
//   .catch((err) => {
//     console.error(err);
//     process.exit(1);
//   });

const playerSeed = [
  {
    firstName: "Troy",
    lastName: "Jamieson",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "tjamieson0@twitpic.com",
    cellphone: "(184) 9818462",
    oPosition: "WR",
    dPosition: "DE",
    number: 1,
  },
  {
    firstName: "Tobie",
    lastName: "Simonetto",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "tsimonetto1@yellowbook.com",
    cellphone: "(903) 3209396",
    oPosition: "FB",
    dPosition: "CB",
    number: 2,
  },
  {
    firstName: "Randie",
    lastName: "Pentony",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "rpentony2@sun.com",
    cellphone: "(864) 4172046",
    oPosition: "OG",
    dPosition: "CB",
    number: 3,
  },
  {
    firstName: "Orrin",
    lastName: "Brinsford",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "obrinsford3@springer.com",
    cellphone: "(674) 9254284",
    oPosition: "TE",
    dPosition: "DT",
    number: 4,
  },
  {
    firstName: "Lennard",
    lastName: "Digby",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "ldigby4@china.com.cn",
    cellphone: "(812) 1380861",
    oPosition: "RB",
    dPosition: "OLB",
    number: 5,
  },
  {
    firstName: "Damien",
    lastName: "Skeats",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "dskeats5@mayoclinic.com",
    cellphone: "(515) 2975312",
    oPosition: "FB",
    dPosition: "DT",
    number: 6,
  },
  {
    firstName: "Frants",
    lastName: "Curme",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "fcurme6@infoseek.co.jp",
    cellphone: "(783) 5550353",
    oPosition: "C",
    dPosition: "CB",
    number: 7,
  },
  {
    firstName: "Tobie",
    lastName: "Stolze",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "tstolze7@state.tx.us",
    cellphone: "(480) 3193305",
    oPosition: "C",
    dPosition: "CB",
    number: 8,
  },
  {
    firstName: "Raimund",
    lastName: "Kemmer",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "rkemmer8@globo.com",
    cellphone: "(639) 8761905",
    oPosition: "WR",
    dPosition: "OLB",
    number: 9,
  },
  {
    firstName: "Nye",
    lastName: "Crates",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "ncrates9@cargocollective.com",
    cellphone: "(978) 7179170",
    oPosition: "TE",
    dPosition: "CB",
    number: 10,
  },
  {
    firstName: "Thayne",
    lastName: "Tidbold",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "ttidbolda@trellian.com",
    cellphone: "(946) 3124305",
    oPosition: "C",
    dPosition: "OLB",
    number: 11,
  },
  {
    firstName: "Torr",
    lastName: "Watters",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "twattersb@usatoday.com",
    cellphone: "(247) 9341530",
    oPosition: "C",
    dPosition: "OLB",
    number: 12,
  },
  {
    firstName: "Faber",
    lastName: "Peck",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "fpeckc@soup.io",
    cellphone: "(642) 3129854",
    oPosition: "RB",
    dPosition: "ILB",
    number: 13,
  },
  {
    firstName: "Lindon",
    lastName: "Waldram",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "lwaldramd@usgs.gov",
    cellphone: "(371) 9323084",
    oPosition: "C",
    dPosition: "SS",
    number: 14,
  },
  {
    firstName: "Domenic",
    lastName: "Greener",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "dgreenere@google.cn",
    cellphone: "(197) 4487099",
    oPosition: "OT",
    dPosition: "DE",
    number: 15,
  },
  {
    firstName: "Dane",
    lastName: "Backes",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "dbackesf@shareasale.com",
    cellphone: "(915) 2228891",
    oPosition: "RB",
    dPosition: "CB",
    number: 16,
  },
  {
    firstName: "Connie",
    lastName: "Spellecy",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "cspellecyg@amazon.de",
    cellphone: "(628) 9701248",
    oPosition: "QB",
    dPosition: "SS",
    number: 17,
  },
  {
    firstName: "Floyd",
    lastName: "Iglesiaz",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "figlesiazh@walmart.com",
    cellphone: "(288) 6525414",
    oPosition: "QB",
    dPosition: "DE",
    number: 18,
  },
  {
    firstName: "Ezechiel",
    lastName: "Paull",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "epaulli@ustream.tv",
    cellphone: "(717) 7917629",
    oPosition: "RB",
    dPosition: "FS",
    number: 19,
  },
  {
    firstName: "Lorne",
    lastName: "Besse",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "lbessej@spiegel.de",
    cellphone: "(670) 4919943",
    oPosition: "WR",
    dPosition: "OLB",
    number: 20,
  },
  {
    firstName: "Frazier",
    lastName: "Bartlet",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "fbartletk@flickr.com",
    cellphone: "(337) 7704056",
    oPosition: "WR",
    dPosition: "FS",
    number: 21,
  },
  {
    firstName: "Abram",
    lastName: "Pregel",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "apregell@latimes.com",
    cellphone: "(192) 3309405",
    oPosition: "OT",
    dPosition: "FS",
    number: 22,
  },
  {
    firstName: "Greg",
    lastName: "Byrd",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "gbyrdm@si.edu",
    cellphone: "(755) 6431361",
    oPosition: "C",
    dPosition: "FS",
    number: 23,
  },
  {
    firstName: "Jeffrey",
    lastName: "Massen",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "jmassenn@mit.edu",
    cellphone: "(857) 9572232",
    oPosition: "TE",
    dPosition: "SS",
    number: 24,
  },
  {
    firstName: "Izak",
    lastName: "Grunwald",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "igrunwaldo@mayoclinic.com",
    cellphone: "(685) 7081925",
    oPosition: "FB",
    dPosition: "CB",
    number: 25,
  },
  {
    firstName: "Huntley",
    lastName: "Jerrams",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "hjerramsp@wunderground.com",
    cellphone: "(452) 6150867",
    oPosition: "RB",
    dPosition: "DT",
    number: 26,
  },
  {
    firstName: "Serge",
    lastName: "Deverson",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "sdeversonq@paypal.com",
    cellphone: "(997) 5706430",
    oPosition: "WR",
    dPosition: "OLB",
    number: 27,
  },
  {
    firstName: "Wallace",
    lastName: "Bugg",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "wbuggr@noaa.gov",
    cellphone: "(645) 9350445",
    oPosition: "RB",
    dPosition: "OLB",
    number: 28,
  },
  {
    firstName: "Aguie",
    lastName: "Gallagher",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "agallaghers@washingtonpost.com",
    cellphone: "(500) 2945824",
    oPosition: "C",
    dPosition: "DT",
    number: 29,
  },
  {
    firstName: "Garner",
    lastName: "Huston",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "ghustont@ucla.edu",
    cellphone: "(456) 6118348",
    oPosition: "RB",
    dPosition: "CB",
    number: 30,
  },
  {
    firstName: "Vail",
    lastName: "Fulks",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "vfulksu@mail.ru",
    cellphone: "(138) 1949487",
    oPosition: "OT",
    dPosition: "CB",
    number: 31,
  },
  {
    firstName: "Federico",
    lastName: "Worsnup",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "fworsnupv@sohu.com",
    cellphone: "(258) 8519699",
    oPosition: "FB",
    dPosition: "SS",
    number: 32,
  },
  {
    firstName: "Donal",
    lastName: "Swettenham",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "dswettenhamw@joomla.org",
    cellphone: "(823) 6679029",
    oPosition: "FB",
    dPosition: "DE",
    number: 33,
  },
  {
    firstName: "Gib",
    lastName: "Goodin",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "ggoodinx@naver.com",
    cellphone: "(264) 6311865",
    oPosition: "OT",
    dPosition: "FS",
    number: 34,
  },
  {
    firstName: "Shamus",
    lastName: "Ardy",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "sardyy@sciencedirect.com",
    cellphone: "(245) 5545239",
    oPosition: "QB",
    dPosition: "DE",
    number: 35,
  },
  {
    firstName: "Lewiss",
    lastName: "Rubinchik",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "lrubinchikz@altervista.org",
    cellphone: "(466) 4673963",
    oPosition: "RB",
    dPosition: "FS",
    number: 36,
  },
  {
    firstName: "Reg",
    lastName: "Garman",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "rgarman10@about.me",
    cellphone: "(449) 7742609",
    oPosition: "C",
    dPosition: "CB",
    number: 37,
  },
  {
    firstName: "Neal",
    lastName: "Gregan",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "ngregan11@imageshack.us",
    cellphone: "(712) 1284566",
    oPosition: "TE",
    dPosition: "OLB",
    number: 38,
  },
  {
    firstName: "Giorgi",
    lastName: "Shuard",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "gshuard12@surveymonkey.com",
    cellphone: "(395) 3675148",
    oPosition: "OT",
    dPosition: "OLB",
    number: 39,
  },
  {
    firstName: "Hendrick",
    lastName: "Yushachkov",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "hyushachkov13@wisc.edu",
    cellphone: "(452) 1013909",
    oPosition: "QB",
    dPosition: "DT",
    number: 40,
  },
  {
    firstName: "Waylon",
    lastName: "Kahane",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "wkahane14@soup.io",
    cellphone: "(840) 6125877",
    oPosition: "OT",
    dPosition: "CB",
    number: 41,
  },
  {
    firstName: "Ashby",
    lastName: "Barbey",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "abarbey15@photobucket.com",
    cellphone: "(694) 8927769",
    oPosition: "QB",
    dPosition: "DE",
    number: 42,
  },
  {
    firstName: "Rudolfo",
    lastName: "Puttick",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "rputtick16@twitpic.com",
    cellphone: "(917) 8164036",
    oPosition: "RB",
    dPosition: "ILB",
    number: 43,
  },
  {
    firstName: "Erny",
    lastName: "Laight",
    teamID: "5eab235fd0d01c678e74e9f8",
    email: "elaight17@nasa.gov",
    cellphone: "(918) 2640484",
    oPosition: "FB",
    dPosition: "ILB",
    number: 44,
  },
];

db.Team.updateMany({}, { $push: { players: playerSeed } })
  .then((dbModel) => {
    console.log("you did it!");
  })
  .catch((err) => res.status(422).json(err));
